import type { Metadata } from "next";
import Link from "next/link";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import { client } from "@/sanity/lib/client";
import { PAGES_QUERY } from "@/sanity/lib/queries";
import type { PAGES_QUERYResult } from "@/sanity/types";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "wyss.rocks",
  description: "Generated by NextJS and Sanity",
};

export const revalidate = 300;

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pages = await client.fetch<PAGES_QUERYResult>(PAGES_QUERY);
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="flex items-center justify-between p-4 bg-gray-800 text-white">
          <Link href="/" className="text-2xl font-bold">
            wyss.rocks
          </Link>
          <nav>
            <ul>
              {pages.map((page) => (
                <li key={page._id}>
                  <Link href={`/${page?.slug?.current}`}>{page?.title}</Link>
                </li>
              ))}
            </ul>
          </nav>
        </header>
        <main className="container mx-auto p-4">{children}</main>
      </body>
    </html>
  );
}
