import type { Metadata } from "next";
import "../globals.css";

export const metadata: Metadata = {
  title: "wyss.rocks",
  description: "Generated by NextJS and Sanity",
};

export default async function EditLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
